# Generated by Django 4.1.5 on 2023-08-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
