# Generated by Django 4.1.5 on 2023-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_userlogin_last_login_userlogin_active_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='active_login',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
